name: Deploy to IIS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted]   # Windows self-hosted runner with IIS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish to folder
        run: dotnet publish --configuration Release --no-build --output C:\inetpub\sites\data.vonet.org

      # Set env vars IIS will read at runtime
      - name: Set connection string (machine scope)
        shell: powershell
        env:
          CONN: ${{ secrets.ConnectionStrings__DefaultConnection }}
        run: |
          if (-not $env:CONN) { throw "GitHub secret ConnectionStrings__DefaultConnection is missing." }
          setx ConnectionStrings__DefaultConnection "$env:CONN" /M
          # Optional: set environment name
          setx ASPNETCORE_ENVIRONMENT "Production" /M

      # Recycle app pool so it picks up the new env vars
      - name: Restart App Pool
        shell: powershell
        run: |
          Stop-WebAppPool -Name "data.vonet.org"
          Start-WebAppPool -Name "data.vonet.org"
