name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Stop App Pool
        run: Stop-WebAppPool -Name "data.vonet.org"
        shell: powershell

      - name: Publish to IIS
        run: dotnet publish --configuration Release --no-build --output C:\inetpub\sites\data.vonet.org

      - name: Set Connection String in IIS
        shell: powershell
        run: |
          Import-Module WebAdministration
          $connectionString = "${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}"
          if (-not $connectionString) {
            throw "Connection string secret is not set!"
          }
          # Set the connection string and environment on the App Pool
          Set-ItemProperty -Path "IIS:\AppPools\data.vonet.org" -Name "environmentVariables" -Value @{ Name = "ASPNETCORE_ENVIRONMENT"; Value = "Production" }, @{ Name = "ConnectionStrings__DefaultConnection"; Value = $connectionString }
          Write-Host "Successfully set environment variables for App Pool 'data.vonet.org'."

      - name: Start App Pool
        run: Start-WebAppPool -Name "data.vonet.org"
        shell: powershell
