name: Deploy to IIS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish app
      run: dotnet publish -c Release -o publish

    - name: Deploy to IIS
      run: |
        & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
          -source:contentPath="$(pwd)\publish" `
          -dest:contentPath=data.vonet.org,ComputerName=$env:PUBLISH_URL,UserName=$env:PUBLISH_USERNAME,Password=$env:PUBLISH_PASSWORD,AuthType=Basic `
          -verb:sync `
          -allowUntrusted
      env:
        PUBLISH_URL: ${{ secrets.PUBLISH_URL }}
        PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
        PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
